### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by diegocouto** [diegocouto/guidde#7]
**As an author:**

* I want to easily understand how helpful Guidde can be to me;
* I need quick & simple getting started instructions;
* I want to know how to deploy my own knowledge base;

**Comment by aaronzshey** [comment]
Uh I could help, but I'm not quite sure how to start this app on my own machine or even what it does - could you give me some pointers to start?

**Comment by diegocouto** [comment]
Thanks, @CarlyRaeJepsenStan! Actually, these issues were created just to help me keep track of the things I still have to do before v1.0 gets released. I do appreciate your help but this is something I still have to work on before we get to a point where community support is needed. 😄

Thanks a lot once again!

**Comment by aaronzshey** [comment]
No problem!  If you ever need help, just ping me :+1:

**Comment by diegocouto** [comment]
A basic [README has been added](https://github.com/diegocouto/guidde/commit/8c7f82a580c25eeb7fbfe0d657b02cf3dd109ae0)!
